services:

  mysql:
    image: mysql:8.0
    container_name: mysql_sistema_kanban_ti
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: sistema_kanban_ti
    command: --default-authentication-plugin=mysql_native_password

    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
